export HOME="/home/simon"
export PATH="$PATH:$HOME/.scripts"
export EDITOR="vim"
export TERMINAL="urxvt"
export BROWSER="firefox"
export READER="zathura"
export FILE="ranger"
export LANG="en_GB.UTF-8"
export TERM=rxvt-unicode-256color
export STARDICT_DATA_DIR="$HOME/.dic"
export XDG_CONFIG_HOME="$HOME/.config"
  
##---PATHS---##
export LOG="$HOME/.log"
export DIV="$HOME/.div"
export CONFIG="$HOME/.config"
export LOCALBIN="$HOME/.bin"
export DOTFILES="$HOME/.dotfiles"
export DOWNLOADS="$HOME/Downloads"
export DOCUMENTS="$HOME/Documents"
export PICTURES="$HOME/Pictures"
export DEV="$HOME/dev"
