#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to search Amazon
# elvis: amazon		-- Search amazon (amazon.co.uk)
. surfraw || exit 1

/usr/lib/surfraw/amazon -country=uk $@
