#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to search DuckDuckGo
# elvis: duckduckgo	-- Securely search the web using duckduckgo (duckduckgo.com)
. surfraw || exit 1

/usr/lib/surfraw/duckduckgo -j $@
