#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 18 2020
#
# DESC: Elvi to search gitlab git projects
# elvis: gitlab		-- Search gitlab for git projects (www.gitlab.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search gitlab (gitlab.com) for git projects
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://gitlab.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://gitlab.com/explore?utf8=%E2%9C%93&name=${escaped_args}&sort=latest_activity_desc"
fi
