#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to search Google Maps
# elvis: gmaps		-- Search google maps (www.google.com/maps)
. surfraw || exit 1

surfraw google -search=maps $@
