#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to search BBC iPlayer
# elvis: iplayer		-- Search BBC iPlayer (www.bbc.co.uk/iplayer)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search BBC iPlayer (www.bbc.co.uk/iplayer)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "www.bbc.co.uk/iplayer"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.bbc.co.uk/search?q=${escaped_args}"
fi
