#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: 19 Oct 2020
#
# DESC: Elvi to search openstreetmap
# elvis: openstreetmap	-- Search openstreetmap (www.openstreetmap.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search openstreetmap (openstreetmap.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://openstreetmap.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.openstreetmap.org/search?query=${escaped_args}"
fi
