#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to search StartPage
# elvis: startpage	-- Search StartPage (www.startpage.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search StartPage (www.startpage.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.startpage.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.startpage.com/do/search?query=${escaped_args}"
fi
