#!/bin/sh
#
# AUTHOR: Simon H Moore
#
# DATE: Wed Oct 07 2020
#
# DESC: Elvi to directly go to url
# elvis: url		-- Directly go to URL
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Directly go to URL
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"

w3_browse_url "$w3_args"
