#!/bin/sh

# export NNNRC
# Simon Hugh Moore
#
# Configuration file for nnn.
# This file needs to be sourced by the shell that runs nnn.

# binary options to nnn
# export NNN_OPTS="cEnrx"

# custom opener (see plugin nuke)
# export NNN_OPENER="/path/to/custom/opener"

# key-bookmark pairs
export NNN_BMS='d:~/Downloads;w:/mnt/wh;D:~/.dotfiles;t:/mnt/wh/torrents'

# key-plugin (or cmd) pairs
# export NNN_PLUG='o:fzopen;m:nmount;x:_chmod +x $nnn'

# context colors [default: '4444' (blue)]
export NNN_COLORS='0253'

# archives [default: bzip2, (g)zip, tar]
# export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"

# custom SSHFS cmd
# export NNN_SSHFS='sshfs -o reconnect,idmap=user'

# custom rclone cmd
# export NNN_RCLONE='rclone mount --read-only'

# use desktop Trash [default: delete]
# export NNN_TRASH=1

# key emulated by middle mouse click
# export NNN_MCLICK='^R'
