#!/bin/sh

# export NNNRC
# Simon Hugh Moore
#
# Configuration file for nnn.
# This file needs to be sourced by the shell that runs nnn.

# binary options to nnn
# export NNN_OPTS="cEnrx"

# key-bookmark pairs
export NNN_BMS="\
n:~/Documents/notes;\
y:~/Videos/youtube.com;\
m:/mnt;\
w:/mnt/wh;\
t:/mnt/wh/torrents;\
F:/mnt/wh/film;\
T:/mnt/wh/tv;\
d:~/Downloads;\
D:~/Documents;\
V:~/Videos;\
P:~/Pictures;\
M:~/Music;\
p:~/projects;\
r:~/repo;\
s:~/sync;\
.:~/.dotfiles;\
R:~/rec\
"

# key-plugin (or cmd) pairs
export NNN_PLUG='p:preview-tabbed;P:preview-tui;d:dups;m:nmount;C:chksum;c:fzcd;f:fzopen;S:suedit;r:!trash-restore'

# context colors [default: '4444' (blue)]
export NNN_COLORS='3256'

# archives [default: bzip2, (g)zip, tar]
export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"

# custom SSHFS cmd
export NNN_SSHFS='sshfs -o reconnect,idmap=user'

# custom rclone cmd
# export NNN_RCLONE='rclone mount --read-only'

# use desktop Trash [default: delete]
export NNN_TRASH=1

# key emulated by middle mouse click
# export NNN_MCLICK='^R'

# absolute path to custom selection file
export NNN_SEL="$XDG_CACHE_HOME/nnn/selection"

# Path path of named pipe to write the hovered file path.
export NNN_RUNTIME="$XDG_RUNTIME_DIR/nnn"
mkdir -p $NNN_RUNTIME
export NNN_FIFO="$NNN_RUNTIME/pipe"
