#!/bin/sh

delim="%{F#d5d5d5}|%{F-}"

_keystate() {
    f_color="e82e1e"

    lockline=$(xset -q | grep "Num Lock")

    caplock=$(echo "$lockline" | awk '{print $4}')
    numlock=$(echo "$lockline" | awk '{print $8}')
    scrolllock=$(echo "$lockline" | awk '{print $12}')

    message=""

    [ "$caplock" = "on" ] && message="%{F#$f_color}CAPLOCK $delim"
    [ "$numlock" = "on" ] && message="$message %{F#$f_color}NUMLOCK $delim"
    [ "$scrolllock" = "on" ] && message="$message %{F#$f_color}SCROLLLOCK $delim"

    echo "$message%{F-}"
}

_weather() {
    w="$(curl -s wttr.in?format=%t,%C)"
    desc="${w#*,}"
    temp="${w%,*}"
    
    symbol=""
    case "$desc" in
        "Clear") symbol="🌞";;
        "Sunny") symbol="☀";;
        "Partly cloudy") symbol="⛅";;
        "Cloudy") symbol="☁";;
        "Shower In Vicinity") symbol="💧";;
        *) symbol="$desc";;
    esac
    echo "$symbol $temp"
}

_memory() {
    f_color="C0C000"

    echo "%{F#$f_color}📊 $(free -h | awk '/Mem:/ {print $3 "/" $2}')%{F-}"
    }

_volume() {
    f_color="98C379"

	[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && return 0

	vol=$(pulsemixer --get-volume | awk '{print $1}')

	if [ "$vol" -gt "100" ]; then
		icon="🔊"
	elif [ "$vol" -lt "50" ]; then
		icon="🔈"
	else
		icon="🔉"
	fi

	printf "%%{F#$f_color}%s %s%%\n%%{F-}" "$icon" "$vol"
}

_update() {
    f_color="b29f27"

    updatenr=$(pacman -Qu | grep -v "\[ignored\]" | wc -l)
    [ "$updatenr" != "0" ] && printf "$delim %{F#$f_color} 📦 $updatenr%{F-}"
}

_record() {
    f_color="e82e1e"

	recpid_file="$XDG_RUNTIME_DIR/recordingpid"
	[ -e "$recpid_file" ] && echo "%{F#$f_color}⏺ rec $delim%{F-}"
}

_battery() {
    # Don't run if acpi not available
    command -v acpi > /dev/null 2>&1 || exit 1
    bat_empty=" "
    bat_quarter=" "
    bat_half=" "
    bat_almost=" "
    bat_full=" "

    BAT0=$(acpi -b | awk '/Battery 0/{print $4}' | tr -d ',')
    BAT1=$(acpi -b | awk '/Battery 1/{print $4}' | tr -d ',')

    echo "$delim $BAT0 $BAT1"
}

_uptime() {
    f_color="c98a1e"

    echo "%{F#$f_color}⬆ $(uptime | awk '{print $3}' | cut -d',' -f 1)%{F-}"
}

_desktops() {
    f_color="ffffff"
    b_color="c25704"

    # Change to given desktop with left mouse click
    click_command="bspc desktop -f '&' \& melonbar"

    # Change to last used desktop with left mouse click
    # on active (highlighted) desktop
    active_click_command="bspc desktop -f last.local \& melonbar"

    current=$(bspc query -D -d --names)
    color_current="%{F#$f_color}%{B#$b_color}%{A:$active_click_command:} $current %{A}%{F-}%{B-}"

    desktops=$(bspc query -D --names | sed "s/^.*$/%{A:$click_command:}&%{A}/g;s/^%{A:.* '$current' .*:}$current%{A}$/$color_current/g")

    # Uncomment to show desktops without clickable areas.
    # desktops=$(bspc query -D --names | sed "s/^$current$/$color_current/g")

    echo "$desktops%{F-}%{B-}"
}

_time() {
    f_color="61AEEE"
    echo "%{F#$f_color}🕒 $(date '+%H:%M')%{F-}"
}

_date() {
    f_color="F79494"
    echo "%{F#$f_color}📅 $(date '+%a %d %B %Y')%{F-}"
}

status() {
    echo "%{l}"
    _desktops

    echo "%{r}"
    _keystate

	# record

    _uptime
    echo "$delim"

    _memory 
    echo "$delim"
    
	_volume
	echo "$delim"

    _date
    echo "$delim"

    _time

    _battery

    # update
}

status | tr '\n' ' ' && echo
