#! /bin/sh

# Remove all previously set rules.
bspc rule -r "*"

if [ "$USER" = "simon" ]; then
    # set up desktops for each monitor.
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 'V'

    # set default layout for Video desktop
    bspc desktop 'V' --layout monocle
else
    bspc monitor -d 1
fi

# config options
bspc config border_width          2     # width of border around window.
bspc config window_gap            12    # size of gap between windows.
bspc config split_ratio           0.52

bspc config borderless_monocle    true  # no borders in monocle layout.
bspc config gapless_monocle       true  # no gaps in monocle layout.
bspc config single_monocle        true  # use monocle layout if there is only 1 window.

# bspc config focus_follows_pointer true # focus the window under the pointer.
# bspc config pointer_follows_focus true # move pointer to focused window.
bspc config pointer_modifier mod1      # modifier to move/resize window with pointer
bspc config ignore_ewmh_focus     true # prevent apps from stealing focus.

# Color
bspc config normal_border_color   "#333333"
bspc config focused_border_color  "#c204b3"
bspc config active_border_color  "#c204b3"
bspc config presel_feedback_color  "#5504c2"

# external rules
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"

# Rules
if [ "$USER" = "simon" ]; then
    bspc rule -a mpv desktop='V'     # open mpv in a dedicated video desktop.
    bspc rule -a mpv focus=off       # don't give new mpv windows focus.
fi
bspc rule -a Zathura state=tiled # open zathura in tiled mode.
bspc rule -a Emacs state=tiled   # open emacs in tiled mode.
bspc rule -a Sype state=tiled   # open skype in tiled mode.

# run bspwm specific sxhkd config.
sxhkd -c "$HOME/.config/sxhkd/bspwm.sxhkdrc" > ~/.local/share/sxhkd/bspwm.sxhkd.log 2>&1 & # keybindings.
# run lemonbar panel after sleep to give system time to catch up.
sleep 1 && melonbar run &
