#! /bin/sh

sxhkd -c "$HOME/.config/sxhkd/bspwm.sxhkdrc" &
melonbar run &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 'V'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# prevent apps from stealing focus
bspc config ignore_ewmh_focus true

# Color
bspc config normal_border_color "#333333"
bspc config focused_border_color "#C25704"

# Rules
bspc rule -a mpv desktop='V'
bspc rule -a Zathura state=tiled
