#!/bin/sh

# EXTERNAL_RULES
# Simon Hugh Moore
#
# Configure bspwm nodes.

wid=$1
class=$2
instance=$3

case "$instance" in
    dropdown*)
        xdo move -x 10 -y 10 $wid
        xdo resize -w 1900 -h 200 $wid

        echo "state=floating"
        echo "sticky=on"
        # echo "hidden=off"
    ;;
    calc)
        xdo resize -w 1200 -h 400 $wid

        echo "state=floating"
        echo "sticky=on"
        # echo "hidden=off"
    ;;
esac
