#!/bin/sh

# EXTERNAL_RULES
# Simon Hugh Moore
#
# Configure bspwm nodes.

wid=$1
class=$2
instance=$3

case "$instance" in
    dropdown*)
        xdotool windowmove $wid 0 -10
        xdotool windowsize $wid 100% 210

        echo "state=floating"
        echo "sticky=on"
        echo "border=off"
    ;;
    powermenu)
        xdotool windowmove $wid 35% 35%
        xdotool windowsize $wid 500 300
        echo "state=floating"
        echo "sticky=on"
        echo "border=off"
    ;;
    calc)
        xdotool windowmove $wid 25% 35%
        xdotool windowsize $wid 1200 400

        echo "state=floating"
        echo "sticky=on"
        # echo "hidden=off"
    ;;
    *_menu)
        xdotool windowmove $wid 30% 30%
        xdotool windowsize $wid 800 400

        echo "state=floating"
        echo "sticky=on"
        echo "border=off"
    ;;
esac
