#!/usr/bin/env sh

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    cat "$selection" | xargs -0 -P 10 -I {} open "{}"

else
    echo "needs at least 1 filee or directorie selected to be opened"
fi
