#!/bin/sh

delim="%{F#d5d5d5}|"

_keystate() {
    lockline=$(xset -q | grep "Num Lock")

    caplock=$(echo "$lockline" | awk '{print $4}')
    numlock=$(echo "$lockline" | awk '{print $8}')
    scrolllock=$(echo "$lockline" | awk '{print $12}')

    message=""

    [ "$caplock" = "on" ] && message="%{F#e82e1e%{FAPLOCK $delim"
    [ "$numlock" = "on" ] && message="$message %{F#e82e1e}NUMLOCK $delim"
    [ "$scrolllock" = "on" ] && message="$message %{F#e82e1e}SCROLLLOCK $delim"

    echo "$message"
}

_weather() {
    w="$(curl -s wttr.in?format=%t,%C)"
    desc="${w#*,}"
    temp="${w%,*}"
    
    symbol=""
    case "$desc" in
        "Clear") symbol="🌞";;
        "Sunny") symbol="☀";;
        "Partly cloudy") symbol="⛅";;
        "Cloudy") symbol="☁";;
        "Shower In Vicinity") symbol="💧";;
        *) symbol="$desc";;
    esac
    echo "$symbol $temp"
}

_memory() {
    free -h | awk '/Mem:/ {print $3 "/" $2}'
}

_volume() {
	[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && return 0

	vol=$(pulsemixer --get-volume | awk '{print $1}')

	if [ "$vol" -gt "100" ]; then
		icon="🔊"
	elif [ "$vol" -lt "50" ]; then
		icon="🔈"
	else
		icon="🔉"
	fi

	printf "%s %s%%\n" "$icon" "$vol"
}

_update() {
    updatenr=$(pacman -Qu | grep -v "\[ignored\]" | wc -l)
    [ "$updatenr" != "0" ] && printf "$delim %{F#b29f27} 📦 $updatenr"
}

_record() {
	recpid_file="$XDG_RUNTIME_DIR/recordingpid"
	[ -e "$recpid_file" ] && echo "%{F#e82e1e}⏺ rec $delim"
}

_battery() {
    # Don't run if acpi not available
    command -v acpi > /dev/null 2>&1 || exit 1
    bat_empty=" "
    bat_quarter=" "
    bat_half=" "
    bat_almost=" "
    bat_full=" "

    BAT0=$(acpi -b | awk '/Battery 0/{print $4}' | tr -d ',')
    BAT1=$(acpi -b | awk '/Battery 1/{print $4}' | tr -d ',')

    echo "$delim $BAT0 $BAT1"
}

_uptime() {
    uptime | awk '{print $3}' | cut -d',' -f 1
}

_desktops() {
    f_color="%{F#c25704}"
    f_selcolor="%{F#ffffff}"
    b_selcolor="%{B#c25704}"

    current=$(bspc query -D -d --names)
    color_current="$f_selcolor$b_selcolor $current $f_color%{B-}"
    desktops=$(bspc query -D --names | sed "s/^$current$/$color_current/g")

    echo "$f_color$desktops"
}

_time() {
    echo "%{F#61AEEE}🕒 $(date '+%H:%M')%{F-}"
}

_date() {
    echo "%{F#F79494}📅 $(date '+%a %d %B %Y')%{F-}"
}

status() {
    echo "%{l}"
    _desktops

    echo "%{r}"
    # keystate

	# record

    echo "%{F#c98a1e}⬆"
    _uptime
    echo "$delim"

    echo "%{F#C0C000}📊"
    _memory 
    echo "$delim"
    
	echo "%{F#98C379}"
	_volume
	echo "$delim"

    _date
    echo "$delim"

    _time

    _battery

    # update
}

status | tr '\n' ' ' && exit
