setlocal tabstop=2
setlocal softtabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal fileformat=unix
setlocal foldmethod=marker
setlocal foldmarker={,}
setlocal foldnestmax=5
setlocal foldlevel=1
